Board
Doom-2/Tick-Tick pull request #8
Opened 2023-01-25 05:55 UTC by Doom-2

Board entity was added to be able to view and edit goals together

2023-01-25 18:36 UTC, painassasin commented on docker-compose-ci.yaml
> +    image: doom2/tick-tick-frontend:v4.1
Ух ты, сам пересобрал фронт - круто!

2023-01-25 18:43 UTC, painassasin requested changes

2023-01-25 18:43 UTC, painassasin commented on docker-compose-ci.yaml
>        - "81:80"
Чем нам не нравится 80 порт?)

2023-01-25 18:43 UTC, painassasin commented on goals/migrations/0003_create_new_objects.py
> +                updated=timezone.now()
Четыре вызова `timezone.now()` не есть хорошо - везде будет разное время
Корректнее создать переменную `now = timezone.now()`, которую ты подставишь во все поля и время будет одинаковое

2023-01-25 18:43 UTC, painassasin commented on goals/models.py
>      description = models.CharField(verbose_name='description', max_length=255)
Поле должно быть опциональным согласно спеке

2023-01-25 18:43 UTC, painassasin commented on goals/permissions.py
> +        if not request.user.is_authenticated:
 Думаю стоит унаследоваться не от BasePermission, а от IsAuthenticated, чтобы каждый раз не прописывать данную проверку

2023-01-25 18:43 UTC, painassasin commented on goals/serializers.py
> +    # def validate_board(self, value: Board):
Мертвый код дропаем при сдаче на проверку)

2023-01-25 18:43 UTC, painassasin commented on goals/serializers.py
> +            instance.title = validated_data['title']
Метод update - для него есть методы put и patch. Согласно RESTAPI method Patch может изменить модель частично, т.е. если в модели 10 полей, у нас должна быть возможность изменить только 1-2 или 3. В данной реализации при изменении участников, тебе нужно обязательно передавать поле title, даже если ты его менять не собираешься
Нужно поправить так, чтобы поля можно было менять независимо друг от друга

2023-01-25 19:03 UTC, Doom-2 commented on docker-compose-ci.yaml
>        - "81:80"
80 порту на сервере занят. у меня запущен еще один nginx, который проксирует другие аппы (курсовые) и этот в том числе. Поэтому приложение на сервере доступно на 80 порту, можно проверить.

2023-01-25 20:39 UTC, Doom-2 commented on goals/migrations/0003_create_new_objects.py
> +                updated=timezone.now()
Сделано. Commit Bugfix v1.8

2023-01-25 20:39 UTC, Doom-2 commented on goals/models.py
>      description = models.CharField(verbose_name='description', max_length=255)
Сделано. Commit Bugfix v1.8

2023-01-25 20:39 UTC, Doom-2 commented on goals/permissions.py
> +        if not request.user.is_authenticated:
Сделано. Commit Bugfix v1.8

2023-01-25 20:39 UTC, Doom-2 commented on goals/serializers.py
> +    # def validate_board(self, value: Board):
Сделано. Commit Bugfix v1.8

2023-01-25 20:39 UTC, Doom-2 commented on goals/serializers.py
> +            instance.title = validated_data['title']
Сделано. Commit Bugfix v1.8

2023-01-25 20:41 UTC, Doom-2 commented on docker-compose-ci.yaml
> +    image: doom2/tick-tick-frontend:v4.1
Да. Иправил баги, собрал и запушил на свой Docker Hub.

2023-01-26 06:35 UTC, painassasin approved these changes

2023-01-26 09:27 UTC, Doom-2 commented
Feature works fine. Can be merged with master.

2023-01-26 09:27 UTC, merged